### ISSUE TITLE
File type icons' size not scaled well after update

### ISSUE THREAD

**Issue by daijiang** [atom-material/atom-material-ui#264]
After update the atom-material-ui package to version 1.2.10 on Mac OS X, the file type icons (from package file-icons) are not scaled very well:

![Imgur](http://i.imgur.com/bONIVaS.png)

But if I choose the other themes, e.g. Atom dark theme, the file type icons scaled right. 

Any thoughts? Thanks!
![screen shot 2016-04-01 at 10 14 40 pm](https://cloud.githubusercontent.com/assets/1696911/14224127/30eefb12-f857-11e5-9d5a-d4016d37ee2d.png)

**Comment by silvestreh** [comment]
I'm not seeing this with either `bib` or `tex` files. Which would be weird because, as far as I can remember, the theme doesn't mess with icons (…yet)

![captura de pantalla 2016-05-04 a las 13 19 58](https://cloud.githubusercontent.com/assets/1133339/15021058/19a6358e-11fb-11e6-93a8-e0de58153417.png)

Check the contributing guide, there's some info in there to help you submit better bug reports so I can take a better look 😄
