### ISSUE TITLE
Icon in update panel doesn't match theme color

### ISSUE THREAD

**Issue by JamesCoyle** [atom-material/atom-material-ui#293]
The heart/sand timer icon in the update panel doesn't match the theme color. Would be nice if it did.

![image](https://cloud.githubusercontent.com/assets/10384436/15636415/bdb88aa6-25f5-11e6-88aa-95ff8dca01e2.png)

**Comment by silvestreh** [comment]
Some things don't have to match the theme color as they're colored based on their status. I mean, you wouldn't expect an error message to be teal colored, it should be red. Same goes for success, information, and warning.

**Comment by JamesCoyle** [comment]
The blue isn't showing anything though. If it was red, yellow or green showing error, warning or failure sure. But it's always just blue and looks out of place.

**Comment by silvestreh** [comment]
I'm sure it does show on other elements. The update counter in the status bar, for instance, is also blue. The hourglass and magnifier icons that appear while searching or waiting for an async method to finish, are also blue. Notifications are blue when they're of type `info` (like this `atom.notifications.addInfo('test');`.)

In short: the `info` status is colored blue. Many packages use the `text-info` class and expect it to be colored blue.

Check Atom's style guide, the _Text classes_ section specifically. Here's what it looks like:

![captura de pantalla 2016-05-29 a las 21 51 30](https://cloud.githubusercontent.com/assets/1133339/15637095/8ceaaa3e-25e7-11e6-9dfd-6b3ab6ab8413.png)

In that screenshot the _"highlighted"_ text will change to match the theme's main color.

In my case is purple because I love how it kinda matches one of my favorite anime pieces 😁 

![](http://vignette2.wikia.nocookie.net/evangelion/images/6/65/Eva-01_handgun.png)
