### ISSUE TITLE
Material Ui and Nuclide issue

### ISSUE THREAD

**Issue by imtiazwazir** [atom-material/atom-material-ui#320]
<img width="241" alt="screen shot 2016-08-23 at 2 38 35 am" src="https://cloud.githubusercontent.com/assets/1964969/17872802/47b0c232-68db-11e6-9ed4-97f0ae15ba39.png">

**Comment by silvestreh** [comment]
Nuclide is _**much**_ better in the `2.0` branch. I'm kinda waiting for Atom `1.17` to hit before I release the latest Material UI because of the updated LESS version which supports optional imports.

Every package is better in the `2.0` branch because I'm no longer fighting against Bootstrap; I'm trying to embrace it and stop doing things _my_ way. Things will be much smoother.

Here's what Nuclide looks like in `2.0`:

![captura de pantalla 2017-03-21 a las 15 42 20](https://cloud.githubusercontent.com/assets/1133339/24164629/1a737a54-0e4d-11e7-810d-46d629e15c04.png)

**Comment by silvestreh** [comment]
Fixed in Material UI `2.0` (available for Atom 1.17-beta)
