### ISSUE TITLE
Project Name CSS for Styling is too restrictive

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom-material/atom-material-ui#352]
Hi @silvestreh 
As reported here in `atom-tree-view-git-status` (https://github.com/subesokun/atom-tree-view-git-status/issues/37), when users give their focus on tree panel, the branch info will become invisible (override by the theme css). Hopefully you can fix this when you have time. Thanks.
![image](https://cloud.githubusercontent.com/assets/17170199/22714727/e5586f40-ede1-11e6-84b0-34f489fb2608.png)
![image](https://cloud.githubusercontent.com/assets/17170199/22714732/e9a271b8-ede1-11e6-84c3-a46a8da9a114.png)

**Comment by silvestreh** [comment]
This is fixed in Material UI `2.0`. It's available for Atom 1.17-beta users!

<img width="282" alt="captura de pantalla 2017-05-04 a la s 16 10 15" src="https://cloud.githubusercontent.com/assets/1133339/25720703/3b5e7098-30e4-11e7-9d7d-dd0b8d3467df.png">
<img width="282" alt="captura de pantalla 2017-05-04 a la s 16 10 32" src="https://cloud.githubusercontent.com/assets/1133339/25720704/3b65d4d2-30e4-11e7-9103-dbbda7586264.png">
