### ISSUE TITLE
Finding with options out of the header container

### ISSUE THREAD

**Issue by davidbarredo** [atom-material/atom-material-ui#375]
Finding with options out of the header container

**Reproduction Steps:**

1. Open Atom editor
2. Press `CMD + F`

**Expected behavior:**
The options in the finding header should be inside it

**Observed behavior:**
The options (floated) are outside the header

**Screenshots and GIFs**
<img width="759" alt="screen shot 2017-03-25 at 11 32 11" src="https://cloud.githubusercontent.com/assets/657206/24321537/ffcfb578-114e-11e7-97e4-dc3c26b2dcc8.png">

**Atom version:** 1.15.0
**OS and version:** macOS Sierra 10.12.3

**Installed packages:**
Material UI theme with Atom Dark syntax

**Comment by silvestreh** [comment]
This is fixed in `2.0` available for Atom 1.17-beta.

<img width="499" alt="captura de pantalla 2017-05-04 a la s 15 53 23" src="https://cloud.githubusercontent.com/assets/1133339/25720048/dc5b6e2c-30e1-11e7-8afe-771d8753bc2d.png">

Falls to the next line just before colliding

<img width="439" alt="captura de pantalla 2017-05-04 a la s 15 53 35" src="https://cloud.githubusercontent.com/assets/1133339/25720052/df045cb0-30e1-11e7-80a8-86a11164f491.png">
